export type EventTimingCategory =
  | 'sports'
  | 'fashion'
  | 'music'
  | 'sneaker'
  | 'tv'
  | 'festival'
  | 'concept'
  | 'other'

export type EventTimingRecord = {
  id: string
  name: string
  category: EventTimingCategory
  fitScore: number
  startDate?: string
  endDate?: string
  usualWindow: string
  statusNote: string
  bestUse: string
  contentAngle: string
  sourceName: string
  sourceUrl?: string
  sourcePublishedAt?: string
  verifiedAt: string
}

export type EventPhase = 'upcoming' | 'today' | 'past' | 'concept' | 'tba'

export const eventCategoryLabels: Record<EventTimingCategory, string> = {
  sports: 'Sports',
  fashion: 'Fashion',
  music: 'Music',
  sneaker: 'Sneaker',
  tv: 'TV / Stage',
  festival: 'Festival',
  concept: 'Concept',
  other: 'Khac / Other',
}

type FlexibleEventInput = {
  id: string
  name: string
  category: EventTimingCategory
  fitScore: number
  usualWindow: string
  bestUse: string
  contentAngle: string
  sourceName?: string
}

function createFlexibleEvent(input: FlexibleEventInput): EventTimingRecord {
  return {
    id: input.id,
    name: input.name,
    category: input.category,
    fitScore: input.fitScore,
    usualWindow: input.usualWindow,
    statusNote: 'Flexible format from the pasted show list. Verify exact date before posting as real news.',
    bestUse: input.bestUse,
    contentAngle: input.contentAngle,
    sourceName: input.sourceName ?? 'Pasted show list',
    verifiedAt: '2026-06-17',
  }
}

const flexibleShowRecords: EventTimingRecord[] = [
  createFlexibleEvent({
    id: 'nba-tunnel-fit-awards',
    name: 'NBA Tunnel Fit Awards',
    category: 'concept',
    fitScore: 10,
    usualWindow: 'Flexible / during NBA season',
    bestUse: 'Judge player outfits like a runway or awards show.',
    contentAngle: 'NBA tunnel fits become a full fashion awards night.',
  }),
  createFlexibleEvent({
    id: 'courtside-couture-concert',
    name: 'Courtside Couture Concert',
    category: 'concept',
    fitScore: 10,
    usualWindow: 'Flexible',
    bestUse: 'Basketball stage, catwalk, live singer, and seated audience.',
    contentAngle: 'Courtside couture turns a basketball arena into a runway concert.',
  }),
  createFlexibleEvent({
    id: 'wnba-fashion-music-night',
    name: 'WNBA Fashion Music Night',
    category: 'concept',
    fitScore: 9,
    usualWindow: 'Flexible / WNBA season',
    bestUse: 'WNBA stars as fashion icons with live music.',
    contentAngle: 'WNBA stars headline a glam fashion-music night.',
  }),
  createFlexibleEvent({
    id: 'hoops-haute-couture',
    name: 'Hoops & Haute Couture',
    category: 'concept',
    fitScore: 9,
    usualWindow: 'Flexible',
    bestUse: 'Luxury streetwear, basketball, runway, and music.',
    contentAngle: 'Hoops and high fashion collide on a celebrity runway.',
  }),
  createFlexibleEvent({
    id: 'la-fashion-week',
    name: 'Los Angeles Fashion Week',
    category: 'fashion',
    fitScore: 8,
    usualWindow: 'Seasonal fashion calendar',
    bestUse: 'NBA stars in LA with Hollywood celebrities.',
    contentAngle: 'An LA basketball star dominates fashion week front row.',
  }),
  createFlexibleEvent({
    id: 'miami-swim-week',
    name: 'Miami Swim Week',
    category: 'fashion',
    fitScore: 7,
    usualWindow: 'Usually summer',
    bestUse: 'Summer, resort, beachwear, athlete vacation style.',
    contentAngle: 'Basketball celebrities bring courtside style to Miami Swim Week.',
  }),
  createFlexibleEvent({
    id: 'vogue-world',
    name: 'Vogue World',
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Varies by city/year',
    bestUse: 'Fashion, performance, celebrity crowd.',
    contentAngle: 'NBA and WNBA style icons appear at a Vogue World spectacle.',
  }),
  createFlexibleEvent({
    id: 'art-hearts-fashion',
    name: 'Art Hearts Fashion',
    category: 'fashion',
    fitScore: 8,
    usualWindow: 'Seasonal fashion calendar',
    bestUse: 'Flashy young runway visuals and independent fashion.',
    contentAngle: 'A basketball-inspired runway look steals an indie fashion show.',
  }),
  createFlexibleEvent({
    id: 'coterie-new-york',
    name: 'COTERIE New York',
    category: 'fashion',
    fitScore: 5,
    usualWindow: 'Trade-show calendar',
    bestUse: 'Fashion business, buying, brand discovery.',
    contentAngle: 'A sportswear capsule draws attention at a New York fashion trade show.',
  }),
  createFlexibleEvent({
    id: 'magic-las-vegas',
    name: 'MAGIC Las Vegas',
    category: 'fashion',
    fitScore: 6,
    usualWindow: 'Trade-show calendar',
    bestUse: 'Streetwear brands, apparel buyers, sneaker-adjacent concepts.',
    contentAngle: 'A basketball streetwear brand launches at MAGIC Las Vegas.',
  }),
  createFlexibleEvent({
    id: 'billboard-music-awards',
    name: 'Billboard Music Awards',
    category: 'music',
    fitScore: 8,
    usualWindow: 'Varies by year',
    bestUse: 'Pop performers, athletes as guests, red carpet reactions.',
    contentAngle: 'A basketball guest becomes the surprise style moment at Billboard.',
  }),
  createFlexibleEvent({
    id: 'bet-hip-hop-awards',
    name: 'BET Hip Hop Awards',
    category: 'music',
    fitScore: 9,
    usualWindow: 'Usually fall',
    bestUse: 'NBA, rap, streetwear, sneaker culture.',
    contentAngle: 'NBA stars bring tunnel-fit energy to the BET Hip Hop Awards.',
  }),
  createFlexibleEvent({
    id: 'soul-train-awards',
    name: 'Soul Train Awards',
    category: 'music',
    fitScore: 7,
    usualWindow: 'Usually late year',
    bestUse: 'R&B, soul, elegant stage, athlete VIP guests.',
    contentAngle: 'A WNBA fashion icon turns Soul Train night into a style moment.',
  }),
  createFlexibleEvent({
    id: 'cma-awards',
    name: 'CMA / ACM Awards',
    category: 'music',
    fitScore: 5,
    usualWindow: 'Country award calendar',
    bestUse: 'Country/cowboy angle, athlete guest appearance.',
    contentAngle: 'A basketball star surprises fans with a country red-carpet look.',
  }),
  createFlexibleEvent({
    id: 'the-voice',
    name: 'The Voice',
    category: 'tv',
    fitScore: 8,
    usualWindow: 'TV season varies',
    bestUse: 'Guest mentor, surprise singing, duet moment.',
    contentAngle: 'An NBA star shocks The Voice crowd with a live vocal moment.',
  }),
  createFlexibleEvent({
    id: 'american-idol',
    name: 'American Idol',
    category: 'tv',
    fitScore: 7,
    usualWindow: 'TV season varies',
    bestUse: 'Guest judge, supporter in audience, singing concept.',
    contentAngle: 'A basketball celebrity appears at American Idol and steals the spotlight.',
  }),
  createFlexibleEvent({
    id: 'americas-got-talent',
    name: "America's Got Talent",
    category: 'tv',
    fitScore: 8,
    usualWindow: 'TV season varies',
    bestUse: 'Surprise athlete performance, guest appearance, crowd reaction.',
    contentAngle: 'A basketball star joins an AGT act for a viral stage surprise.',
  }),
  createFlexibleEvent({
    id: 'lip-sync-battle',
    name: 'Lip Sync Battle',
    category: 'tv',
    fitScore: 9,
    usualWindow: 'Flexible / archive-style concept',
    bestUse: 'Funny stage performance, costumes, viral celebrity moment.',
    contentAngle: 'A basketball superstar lip-syncs in a runway-level stage outfit.',
  }),
  createFlexibleEvent({
    id: 'i-can-see-your-voice',
    name: 'I Can See Your Voice',
    category: 'tv',
    fitScore: 6,
    usualWindow: 'TV season varies',
    bestUse: 'Celebrity guest guessing singers.',
    contentAngle: 'An NBA guest tries to guess the mystery singer on live TV.',
  }),
  createFlexibleEvent({
    id: 'jimmy-fallon',
    name: 'The Tonight Show Starring Jimmy Fallon',
    category: 'tv',
    fitScore: 9,
    usualWindow: 'Weeknights / guest schedule',
    bestUse: 'Games, singing bits, celebrity interview, viral clips.',
    contentAngle: 'An NBA star surprises the Tonight Show audience with a live song.',
  }),
  createFlexibleEvent({
    id: 'jimmy-kimmel-live',
    name: 'Jimmy Kimmel Live!',
    category: 'tv',
    fitScore: 8,
    usualWindow: 'Weeknights / guest schedule',
    bestUse: 'Interview, jokes, reaction, pop culture.',
    contentAngle: 'A basketball celebrity turns a late-night interview into a fashion moment.',
  }),
  createFlexibleEvent({
    id: 'seth-meyers',
    name: 'Late Night with Seth Meyers',
    category: 'tv',
    fitScore: 7,
    usualWindow: 'Weeknights / guest schedule',
    bestUse: 'Smart interview, culture, sports commentary.',
    contentAngle: 'An athlete breaks down fashion and culture on late night TV.',
  }),
  createFlexibleEvent({
    id: 'stephen-colbert',
    name: 'The Late Show with Stephen Colbert',
    category: 'tv',
    fitScore: 6,
    usualWindow: 'Weeknights / guest schedule',
    bestUse: 'Interview with social or cultural angle.',
    contentAngle: 'A basketball star brings sports, style, and culture to late night.',
  }),
  createFlexibleEvent({
    id: 'watch-what-happens-live',
    name: 'Watch What Happens Live',
    category: 'tv',
    fitScore: 8,
    usualWindow: 'Guest schedule varies',
    bestUse: 'Drama, dating rumor, pop culture.',
    contentAngle: 'A basketball guest faces rapid-fire fashion and relationship questions.',
  }),
  createFlexibleEvent({
    id: 'the-view',
    name: 'The View',
    category: 'tv',
    fitScore: 8,
    usualWindow: 'Weekday guest schedule',
    bestUse: 'WNBA, culture, debate, women in sports.',
    contentAngle: 'A WNBA star discusses fashion, pressure, and fame on daytime TV.',
  }),
  createFlexibleEvent({
    id: 'jennifer-hudson-show',
    name: 'The Jennifer Hudson Show',
    category: 'tv',
    fitScore: 8,
    usualWindow: 'Daytime guest schedule',
    bestUse: 'Singing, emotional celebrity story, audience warmth.',
    contentAngle: 'A basketball guest shares a heartfelt story before a surprise duet.',
  }),
  createFlexibleEvent({
    id: 'kelly-clarkson-show',
    name: 'The Kelly Clarkson Show',
    category: 'tv',
    fitScore: 9,
    usualWindow: 'Daytime guest schedule',
    bestUse: 'Cover, duet, musician-athlete surprise.',
    contentAngle: 'An NBA star joins Kelly Clarkson for a surprise cover performance.',
  }),
  createFlexibleEvent({
    id: 'drew-barrymore-show',
    name: 'The Drew Barrymore Show',
    category: 'tv',
    fitScore: 7,
    usualWindow: 'Daytime guest schedule',
    bestUse: 'Soft celebrity story, lifestyle, light fashion.',
    contentAngle: 'A basketball guest opens up about style, family, and fame.',
  }),
  createFlexibleEvent({
    id: 'wild-n-out',
    name: "Wild 'N Out",
    category: 'tv',
    fitScore: 9,
    usualWindow: 'TV season varies',
    bestUse: 'Rap battle, jokes, hip-hop, athlete cameo.',
    contentAngle: 'An NBA star enters a Wild N Out rap battle in full streetwear.',
  }),
  createFlexibleEvent({
    id: 'whose-line',
    name: 'Whose Line Is It Anyway?',
    category: 'tv',
    fitScore: 6,
    usualWindow: 'TV season varies',
    bestUse: 'Improv comedy and athlete guest appearance.',
    contentAngle: 'A basketball star tries live improv and wins over the crowd.',
  }),
  createFlexibleEvent({
    id: 'celebrity-variety-night',
    name: 'Celebrity Variety Night',
    category: 'concept',
    fitScore: 9,
    usualWindow: 'Flexible',
    bestUse: 'Music, comedy, fashion, celebrity cameos.',
    contentAngle: 'A celebrity variety night becomes a basketball-fashion crossover.',
  }),
  createFlexibleEvent({
    id: 'oscars',
    name: 'Oscars',
    category: 'other',
    fitScore: 7,
    usualWindow: 'Usually February or March',
    bestUse: 'Presenter, luxury red carpet, Hollywood crossover.',
    contentAngle: 'A basketball superstar walks the Oscars carpet in cinematic couture.',
  }),
  createFlexibleEvent({
    id: 'emmys',
    name: 'Emmys',
    category: 'other',
    fitScore: 6,
    usualWindow: 'Usually September',
    bestUse: 'TV documentary, athlete presenter, red carpet.',
    contentAngle: 'An athlete documentary star arrives at the Emmys in designer tailoring.',
  }),
  createFlexibleEvent({
    id: 'golden-globes',
    name: 'Golden Globes',
    category: 'other',
    fitScore: 7,
    usualWindow: 'Usually January',
    bestUse: 'Hollywood tables, celebrity reactions, red carpet.',
    contentAngle: 'A basketball guest becomes the unexpected Golden Globes style moment.',
  }),
  createFlexibleEvent({
    id: 'sag-awards',
    name: 'SAG Awards',
    category: 'other',
    fitScore: 5,
    usualWindow: 'Usually winter',
    bestUse: 'Acting/docuseries link, subtle red carpet.',
    contentAngle: 'A sports documentary cast brings athlete style to the SAG Awards.',
  }),
  createFlexibleEvent({
    id: 'peoples-choice-awards',
    name: "People's Choice Awards",
    category: 'other',
    fitScore: 8,
    usualWindow: 'Varies by year',
    bestUse: 'Fan voting, celebrity, pop-culture red carpet.',
    contentAngle: 'A fan-favorite basketball star wins the red carpet conversation.',
  }),
  createFlexibleEvent({
    id: 'mtv-movie-tv-awards',
    name: 'MTV Movie & TV Awards',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Varies by year',
    bestUse: 'Youthful, viral, athlete cameo.',
    contentAngle: 'An NBA cameo turns MTV Movie and TV night into a style clip.',
  }),
  createFlexibleEvent({
    id: 'kids-choice-awards',
    name: "Nickelodeon Kids' Choice Awards",
    category: 'other',
    fitScore: 7,
    usualWindow: 'Usually spring',
    bestUse: 'Fun family audience, bright colors, slime moment.',
    contentAngle: 'A basketball star gets slimed after a surprise stage appearance.',
  }),
  createFlexibleEvent({
    id: 'nike-basketball-launch',
    name: 'Nike Basketball Launch Event',
    category: 'sneaker',
    fitScore: 10,
    usualWindow: 'No fixed public calendar',
    bestUse: 'Signature shoe reveal, athlete keynote, product stage.',
    contentAngle: 'A Nike signature shoe launch becomes a full fashion-music event.',
  }),
  createFlexibleEvent({
    id: 'adidas-basketball-launch',
    name: 'Adidas Basketball Launch',
    category: 'sneaker',
    fitScore: 9,
    usualWindow: 'No fixed public calendar',
    bestUse: 'Young athletes, streetwear, LED stage.',
    contentAngle: 'Adidas turns a basketball launch into a streetwear runway.',
  }),
  createFlexibleEvent({
    id: 'puma-basketball-event',
    name: 'Puma Basketball Event',
    category: 'sneaker',
    fitScore: 8,
    usualWindow: 'No fixed public calendar',
    bestUse: 'Young stars, lifestyle, rapper performance.',
    contentAngle: 'A Puma basketball event brings athletes and rappers onto one stage.',
  }),
  createFlexibleEvent({
    id: 'new-balance-basketball-event',
    name: 'New Balance Basketball Event',
    category: 'sneaker',
    fitScore: 8,
    usualWindow: 'No fixed public calendar',
    bestUse: 'Minimal premium athlete-focused brand reveal.',
    contentAngle: 'A clean basketball launch becomes a quiet luxury style moment.',
  }),
  createFlexibleEvent({
    id: 'foot-locker-launch',
    name: 'Foot Locker / Champs Sports Launch',
    category: 'sneaker',
    fitScore: 8,
    usualWindow: 'Retail launch calendar',
    bestUse: 'Fan signing, sneaker reveal, store event.',
    contentAngle: 'A surprise athlete appearance turns a sneaker launch into a fan frenzy.',
  }),
  createFlexibleEvent({
    id: 'gq-sports-style-event',
    name: 'GQ Sports Style Event',
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Flexible / editorial calendar',
    bestUse: 'Fit breakdown, style icon, athlete interviews.',
    contentAngle: 'A basketball style icon breaks down the year best tunnel fits.',
  }),
  createFlexibleEvent({
    id: 'nba-tunnel-fit-exhibition',
    name: 'NBA Tunnel Fit Exhibition',
    category: 'concept',
    fitScore: 10,
    usualWindow: 'Flexible',
    bestUse: 'Museum-style tunnel fit display, fashion archive.',
    contentAngle: 'NBA tunnel fits become a museum-level fashion exhibition.',
  }),
  createFlexibleEvent({
    id: 'lollapalooza',
    name: 'Lollapalooza',
    category: 'festival',
    fitScore: 8,
    usualWindow: 'Usually summer',
    bestUse: 'Large multi-genre festival, celebrity crowd.',
    contentAngle: 'Basketball celebrities bring festival streetwear to Lollapalooza.',
  }),
  createFlexibleEvent({
    id: 'governors-ball',
    name: 'Governors Ball',
    category: 'festival',
    fitScore: 7,
    usualWindow: 'Usually June',
    bestUse: 'New York pop, rap, indie, celebrity sightings.',
    contentAngle: 'NBA stars appear in the VIP crowd at Governors Ball.',
  }),
  createFlexibleEvent({
    id: 'bet-experience',
    name: 'BET Experience',
    category: 'festival',
    fitScore: 10,
    usualWindow: 'Around BET Awards season',
    bestUse: 'Hip-hop, R&B, NBA/WNBA, fan events.',
    contentAngle: 'BET Experience turns into a basketball streetwear showcase.',
  }),
  createFlexibleEvent({
    id: 'essence-festival',
    name: 'Essence Festival',
    category: 'festival',
    fitScore: 9,
    usualWindow: 'Usually summer',
    bestUse: 'Culture, music, fashion, empowerment, WNBA angle.',
    contentAngle: 'WNBA stars bring fashion and empowerment to Essence Festival.',
  }),
  createFlexibleEvent({
    id: 'movie-premiere',
    name: 'Hollywood Movie Premiere',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Film release calendar',
    bestUse: 'Red carpet, actors, singers, athlete guest.',
    contentAngle: 'A basketball superstar stuns at a Hollywood premiere.',
  }),
  createFlexibleEvent({
    id: 'netflix-premiere',
    name: 'Netflix Sports Documentary Premiere',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Release calendar',
    bestUse: 'Sports docuseries, red carpet, athlete interview.',
    contentAngle: 'A sports documentary premiere becomes an athlete fashion night.',
  }),
  createFlexibleEvent({
    id: 'hbo-sports-premiere',
    name: 'HBO Sports Documentary Premiere',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Release calendar',
    bestUse: 'Documentary prestige, athlete panel, red carpet.',
    contentAngle: 'Basketball legends reunite on a documentary premiere carpet.',
  }),
  createFlexibleEvent({
    id: 'tribeca-film-festival',
    name: 'Tribeca Film Festival',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Usually June',
    bestUse: 'Sports documentaries, New York red carpet.',
    contentAngle: 'A basketball documentary premiere draws fashion-heavy celebrity guests.',
  }),
  createFlexibleEvent({
    id: 'amfar-gala',
    name: 'amfAR Gala',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Gala calendar varies',
    bestUse: 'Charity, red carpet, singers, VIP guests.',
    contentAngle: 'Basketball stars walk a luxury charity gala carpet.',
  }),
  createFlexibleEvent({
    id: 'baby2baby-gala',
    name: 'Baby2Baby Gala',
    category: 'other',
    fitScore: 7,
    usualWindow: 'Usually fall',
    bestUse: 'Celebrity charity, fashion, philanthropy.',
    contentAngle: 'An athlete couple turns a charity gala into a fashion headline.',
  }),
  createFlexibleEvent({
    id: 'nba-foundation-gala',
    name: 'NBA Foundation Gala',
    category: 'concept',
    fitScore: 10,
    usualWindow: 'Flexible',
    bestUse: 'Basketball, charity, fashion, live music.',
    contentAngle: 'NBA Foundation Gala becomes a fashion-music night.',
  }),
  createFlexibleEvent({
    id: 'black-excellence-gala',
    name: 'Black Excellence Gala',
    category: 'concept',
    fitScore: 9,
    usualWindow: 'Flexible',
    bestUse: 'R&B, fashion, NBA/WNBA, culture.',
    contentAngle: 'Basketball stars celebrate Black excellence with fashion and live R&B.',
  }),
  createFlexibleEvent({
    id: 'nba-fan-fest',
    name: 'NBA Fan Fest',
    category: 'concept',
    fitScore: 10,
    usualWindow: 'Flexible / around major NBA events',
    bestUse: 'Fans, stage, players, singers, brand booths.',
    contentAngle: 'NBA Fan Fest turns into a surprise fashion and music stage.',
  }),
  createFlexibleEvent({
    id: 'comic-con-panel',
    name: 'Comic-Con Style Panel',
    category: 'other',
    fitScore: 6,
    usualWindow: 'Convention calendar',
    bestUse: 'Film, game, ad campaign, athlete cameo.',
    contentAngle: 'A basketball star surprises fans at a pop-culture panel.',
  }),
  createFlexibleEvent({
    id: 'vidcon',
    name: 'VidCon',
    category: 'other',
    fitScore: 7,
    usualWindow: 'Creator convention calendar',
    bestUse: 'Creators, influencers, YouTube/TikTok athlete crossover.',
    contentAngle: 'A viral basketball creator moment takes over VidCon.',
  }),
  createFlexibleEvent({
    id: 'twitchcon',
    name: 'TwitchCon',
    category: 'other',
    fitScore: 6,
    usualWindow: 'Gaming convention calendar',
    bestUse: 'Streamers, athlete gaming, NBA 2K crossover.',
    contentAngle: 'A basketball star joins streamers for a live gaming challenge.',
  }),
  createFlexibleEvent({
    id: 'louis-vuitton-afterparty',
    name: "Louis Vuitton Men's Show Afterparty",
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Fashion week / brand calendar',
    bestUse: 'Luxury, athlete ambassador, singer performance.',
    contentAngle: 'NBA style icons take over a Louis Vuitton afterparty.',
  }),
  createFlexibleEvent({
    id: 'gucci-party',
    name: 'Gucci Celebrity Party',
    category: 'fashion',
    fitScore: 8,
    usualWindow: 'Brand calendar varies',
    bestUse: 'Luxury outfits, celebrity photos, red carpet.',
    contentAngle: 'A basketball star turns a Gucci party into a viral fashion clip.',
  }),
  createFlexibleEvent({
    id: 'dior-mens-event',
    name: "Dior Men's Event",
    category: 'fashion',
    fitScore: 8,
    usualWindow: 'Brand calendar varies',
    bestUse: 'Suits, athlete ambassador, luxury styling.',
    contentAngle: 'An NBA ambassador arrives at Dior in a sharp tunnel-inspired suit.',
  }),
  createFlexibleEvent({
    id: 'vogue-party',
    name: 'Vogue Dinner / Vogue Party',
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Fashion calendar varies',
    bestUse: 'Editors, celebrities, fashion credibility.',
    contentAngle: 'Basketball style icons join a private Vogue dinner.',
  }),
  createFlexibleEvent({
    id: 'ncaa-final-four-fan-fest',
    name: 'NCAA Final Four Fan Fest',
    category: 'sports',
    fitScore: 8,
    usualWindow: 'Around Final Four',
    bestUse: 'College basketball, fans, sponsor stage, music.',
    contentAngle: 'Final Four Fan Fest becomes a college hoops fashion stage.',
  }),
  createFlexibleEvent({
    id: 'nil-brand-launch',
    name: 'NIL Brand Launch Event',
    category: 'sneaker',
    fitScore: 9,
    usualWindow: 'College sports calendar varies',
    bestUse: 'Young athletes signing fashion or sneaker deals.',
    contentAngle: 'A college basketball star launches an NIL fashion capsule.',
  }),
  createFlexibleEvent({
    id: 'jordan-classic',
    name: 'Jordan Classic Event',
    category: 'sports',
    fitScore: 8,
    usualWindow: 'High-school showcase calendar',
    bestUse: 'Rising stars, sneaker culture, youth basketball.',
    contentAngle: 'Future basketball stars debut tunnel fits at Jordan Classic.',
  }),
  createFlexibleEvent({
    id: 'mcdonalds-all-american',
    name: "McDonald's All-American Game Event",
    category: 'sports',
    fitScore: 7,
    usualWindow: 'High-school showcase calendar',
    bestUse: 'Rising stars, media, family, outfit arrival.',
    contentAngle: 'Teen basketball stars turn All-American arrivals into a runway.',
  }),
  createFlexibleEvent({
    id: 'super-bowl-party',
    name: 'Super Bowl Weekend Party',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Super Bowl weekend',
    bestUse: 'Athletes, rappers, celebrity party, brand activations.',
    contentAngle: 'NBA stars crash a Super Bowl party with luxury tunnel fits.',
  }),
  createFlexibleEvent({
    id: 'super-bowl-halftime',
    name: 'Super Bowl Halftime Show',
    category: 'music',
    fitScore: 8,
    usualWindow: 'Super Bowl Sunday',
    bestUse: 'Massive music stage, athlete cameo, spectacle.',
    contentAngle: 'Basketball icons appear during a halftime-show fashion reveal.',
  }),
  createFlexibleEvent({
    id: 'march-madness-watch-party',
    name: 'March Madness Watch Party',
    category: 'sports',
    fitScore: 7,
    usualWindow: 'March and early April',
    bestUse: 'College basketball fans, big screens, crowd energy.',
    contentAngle: 'A March Madness watch party becomes a campus fashion moment.',
  }),
  createFlexibleEvent({
    id: 'world-cup-watch-party',
    name: 'World Cup Watch Party',
    category: 'other',
    fitScore: 7,
    usualWindow: 'World Cup calendar',
    bestUse: 'International sports, singers, celebrity crowd.',
    contentAngle: 'Athletes from different sports meet at a global watch party.',
  }),
  createFlexibleEvent({
    id: 'espn-live-watch-party',
    name: 'ESPN Live Watch Party',
    category: 'sports',
    fitScore: 7,
    usualWindow: 'Game calendar varies',
    bestUse: 'Studio, live audience, big screens, analysis.',
    contentAngle: 'ESPN turns a live watch party into a celebrity stage.',
  }),
  createFlexibleEvent({
    id: 'the-shop-live',
    name: 'The Shop-style Live Event',
    category: 'other',
    fitScore: 9,
    usualWindow: 'Flexible',
    bestUse: 'Culture talk, NBA, music, lifestyle.',
    contentAngle: 'A barbershop-style live show reveals an athlete fashion collab.',
  }),
  createFlexibleEvent({
    id: 'complex-sneaker-shopping-live',
    name: 'Complex Sneaker Shopping Live',
    category: 'sneaker',
    fitScore: 9,
    usualWindow: 'Flexible / episode schedule',
    bestUse: 'Sneakers, player shopping, fashion talk.',
    contentAngle: 'A basketball star breaks the sneaker budget live on stage.',
  }),
  createFlexibleEvent({
    id: 'gq-fit-check-live',
    name: 'GQ Fit Check Live',
    category: 'fashion',
    fitScore: 8,
    usualWindow: 'Flexible / editorial calendar',
    bestUse: 'Outfit breakdown, audience Q&A, style panel.',
    contentAngle: 'An NBA star breaks down a viral tunnel fit for a live crowd.',
  }),
  createFlexibleEvent({
    id: 'nba-on-tnt-live',
    name: 'NBA on TNT Live Show',
    category: 'sports',
    fitScore: 8,
    usualWindow: 'NBA broadcast calendar',
    bestUse: 'Comedy, basketball, fan audience, panel chemistry.',
    contentAngle: 'NBA on TNT turns a studio segment into a fashion debate.',
  }),
  createFlexibleEvent({
    id: 'nba-2k-launch',
    name: 'NBA 2K Launch Event',
    category: 'other',
    fitScore: 9,
    usualWindow: 'Game release calendar',
    bestUse: 'NBA players, rappers, gaming, digital fashion.',
    contentAngle: 'NBA 2K launch becomes a fashion-music night with rap performers.',
  }),
  createFlexibleEvent({
    id: 'twitch-rivals-basketball',
    name: 'Twitch Rivals Basketball Special',
    category: 'other',
    fitScore: 7,
    usualWindow: 'Gaming event calendar',
    bestUse: 'Streamers, athletes, gaming challenge.',
    contentAngle: 'Basketball stars face streamers in a live gaming showdown.',
  }),
  createFlexibleEvent({
    id: 'fortnite-concert-style',
    name: 'Fortnite Concert-style Event',
    category: 'other',
    fitScore: 7,
    usualWindow: 'Game event calendar',
    bestUse: 'Avatar, digital concert, athlete skin, singer cameo.',
    contentAngle: 'An NBA avatar joins a virtual concert fashion reveal.',
  }),
  createFlexibleEvent({
    id: 'macys-thanksgiving-parade',
    name: "Macy's Thanksgiving Day Parade",
    category: 'other',
    fitScore: 6,
    usualWindow: 'Thanksgiving Day',
    bestUse: 'Family TV, parade float, singer appearance.',
    contentAngle: 'A basketball star appears on a parade float with a live singer.',
  }),
  createFlexibleEvent({
    id: 'new-years-rockin-eve',
    name: "New Year's Rockin' Eve",
    category: 'music',
    fitScore: 7,
    usualWindow: 'December 31',
    bestUse: 'Countdown, pop stage, celebrity appearance.',
    contentAngle: 'A basketball celebrity joins a countdown-stage fashion moment.',
  }),
  createFlexibleEvent({
    id: 'fashion-week-afterparty',
    name: 'Fashion Week After-Party',
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Fashion week nights',
    bestUse: 'Designer, model, NBA star, DJ, paparazzi.',
    contentAngle: 'A fashion week after-party turns into a secret athlete runway.',
  }),
  createFlexibleEvent({
    id: 'grammy-afterparty',
    name: 'Grammy After-Party',
    category: 'music',
    fitScore: 8,
    usualWindow: 'Grammy night',
    bestUse: 'Singers, athletes, VIP party, luxury outfits.',
    contentAngle: 'NBA guests steal attention at a Grammy after-party.',
  }),
  createFlexibleEvent({
    id: 'brand-vip-party',
    name: 'Brand VIP Party',
    category: 'concept',
    fitScore: 9,
    usualWindow: 'Flexible',
    bestUse: 'Sneaker/luxury launch, private singer performance.',
    contentAngle: 'A private brand party becomes a surprise basketball fashion show.',
  }),
  createFlexibleEvent({ id: 'txt-adidas-basketball-fashion-show', name: 'Adidas Basketball Fashion Show', category: 'sneaker', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Streetwear, performance, young athlete vibe', contentAngle: 'Adidas Basketball Fashion Show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-afi-fest-la-premiere', name: 'AFI Fest / LA Premiere', category: 'other', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Sang, Hollywood vibe', contentAngle: 'AFI Fest / LA Premiere works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-after-the-final-rose', name: 'After the Final Rose', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tinh cam/drama, it hop thoi trang', contentAngle: 'After the Final Rose works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-amazon-prime-sports-series-premiere', name: 'Amazon Prime Sports Series Premiere', category: 'sports', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Athlete docuseries, san khau phong van', contentAngle: 'Amazon Prime Sports Series Premiere works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-americas-got-talent-alt', name: 'America’s Got Talent', category: 'tv', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam khach moi, bieu dien bat ngo', contentAngle: 'America’s Got Talent works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-americas-next-top-model-style', name: 'America’s Next Top Model style', category: 'fashion', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam guest judge, runway', contentAngle: 'America’s Next Top Model style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-apple-keynote-sneakers', name: 'Apple-style Keynote but for sneakers', category: 'sneaker', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu dung san khau gioi thieu san pham', contentAngle: 'Apple-style Keynote but for sneakers works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-balenciaga-fashion-party', name: 'Balenciaga Fashion Party', category: 'fashion', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Outfit cuc di, gay tranh cai', contentAngle: 'Balenciaga Fashion Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-beat-shazam', name: 'Beat Shazam', category: 'music', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu doan nhac, co hat ho', contentAngle: 'Beat Shazam works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-bleacher-report-fashion-panel', name: 'Bleacher Report Fashion Panel', category: 'fashion', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tunnel fit, NBA style, influencer', contentAngle: 'Bleacher Report Fashion Panel works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-celebrity-fashion-charity-show', name: 'Celebrity Fashion Charity Show', category: 'fashion', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu di catwalk gay quy', contentAngle: 'Celebrity Fashion Charity Show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-celebrity-guest-episode', name: 'Celebrity guest episode', category: 'tv', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu xuat hien trong tap dac biet', contentAngle: 'Celebrity guest episode works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-cfda-awards', name: 'CFDA Awards', category: 'fashion', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Style icon, designer collab', contentAngle: 'CFDA Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-christmas-tv-special', name: 'Christmas TV Special', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu hat vui/chuc mung, gia dinh', contentAngle: 'Christmas TV Special works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-cma-acm-awards', name: 'CMA Awards / ACM Awards', category: 'music', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Chi hop neu cau thu lien quan country/cowboy vibe', contentAngle: 'CMA Awards / ACM Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-college-basketball-awards', name: 'College Basketball Awards', category: 'sports', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tan binh, san khau, gia dinh', contentAngle: 'College Basketball Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-comedy-central-special', name: 'Comedy Central special', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam guest cameo', contentAngle: 'Comedy Central special works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-complex-sneaker-shopping-style', name: 'Complex Sneaker Shopping-style', category: 'sneaker', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu mua sneaker, noi fashion', contentAngle: 'Complex Sneaker Shopping-style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-dior-mens-event', name: 'Dior Men’s Event', category: 'fashion', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Sang, suit, athlete ambassador', contentAngle: 'Dior Men’s Event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-disney-espn-premiere', name: 'Disney / ESPN Premiere', category: 'sports', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Gia dinh, the thao, truyen hinh', contentAngle: 'Disney / ESPN Premiere works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-disney-holiday-special', name: 'Disney Holiday Special', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Family-friendly, it hop NBA drama', contentAngle: 'Disney Holiday Special works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-espn-first-take-live', name: 'ESPN First Take Live', category: 'sports', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tranh luan the thao, khan gia dong', contentAngle: 'ESPN First Take Live works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-esports-awards', name: 'Esports Awards', category: 'other', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam guest presenter', contentAngle: 'Esports Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-espy-awards', name: 'ESPY Awards', category: 'sports', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Le trao giai the thao, tham do, ca si bieu dien', contentAngle: 'ESPY Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-family-feud', name: 'Family Feud', category: 'tv', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu cung gia dinh/doi bong thi dau', contentAngle: 'Family Feud works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-fanduel-draftkings-sports-event', name: 'FanDuel / DraftKings Sports Event', category: 'sports', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'The thao, celeb, watch party', contentAngle: 'FanDuel / DraftKings Sports Event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-fear-of-god-off-white-supreme-style-event', name: 'Fear of God / Off-White / Supreme style event', category: 'sneaker', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hop tunnel fit, rapper, NBA culture', contentAngle: 'Fear of God / Off-White / Supreme style event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-first-take-style-live-show', name: 'First Take-style live show', category: 'tv', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tranh luan bong ro, outfit, controversy', contentAngle: 'First Take-style live show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-fourth-of-july-concert', name: 'Fourth of July Concert', category: 'music', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'San khau ngoai troi, phao hoa, celeb', contentAngle: 'Fourth of July Concert works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-gaming-fashion-launch', name: 'Gaming Fashion Launch', category: 'fashion', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Digital outfit, sneaker, avatar', contentAngle: 'Gaming Fashion Launch works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-gq-style-fit-breakdown', name: 'GQ-style fit breakdown', category: 'fashion', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu breakdown outfit', contentAngle: 'GQ-style fit breakdown works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-iheartradio-music-festival', name: 'iHeartRadio Music Festival', category: 'music', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'San khau truyen hinh, celeb crowd', contentAngle: 'iHeartRadio Music Festival works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-jeopardy', name: 'Jeopardy!', category: 'tv', fitScore: 4, usualWindow: 'Flexible / verify exact schedule', bestUse: 'It hop viral/fashion', contentAngle: 'Jeopardy! works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-jordan-nike-adidas-fashion-show', name: 'Jordan / Nike / Adidas Fashion Show', category: 'sneaker', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu ra mat sneaker, ao khoac, streetwear, bieu dien live', contentAngle: 'Jordan / Nike / Adidas Fashion Show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-jordan-brand-runway', name: 'Jordan Brand Runway', category: 'sneaker', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu + nguoi mau + hip-hop performance', contentAngle: 'Jordan Brand Runway works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-live-podcast-tour', name: 'Live Podcast Tour', category: 'tv', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu ke chuyen, reveal collab thoi trang', contentAngle: 'Live Podcast Tour works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-louis-vuitton-mens-show-afterparty', name: 'Louis Vuitton Men’s Show Afterparty', category: 'fashion', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'NBA star mac luxury, ca si bieu dien', contentAngle: 'Louis Vuitton Men’s Show Afterparty works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-louis-vuitton-x-nba-concept', name: 'Louis Vuitton x NBA Concept', category: 'fashion', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Sang, cao cap, runway', contentAngle: 'Louis Vuitton x NBA Concept works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-love-is-blind-reunion-style', name: 'Love Is Blind Reunion style', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu vuong dating rumor', contentAngle: 'Love Is Blind Reunion style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-macys-thanksgiving-day-parade', name: 'Macy’s Thanksgiving Day Parade', category: 'other', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu xuat hien tren xe dieu hanh, ca si hat', contentAngle: 'Macy’s Thanksgiving Day Parade works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-made-in-america-festival-style', name: 'Made in America Festival-style', category: 'music', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Rap/pop, streetwear, crowd lon', contentAngle: 'Made in America Festival-style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-mcdonalds-all-american-game-event', name: 'McDonald’s All-American Game Event', category: 'sports', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Sao tre, media, outfit', contentAngle: 'McDonald’s All-American Game Event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-met-gala-after-party', name: 'Met Gala After-Party', category: 'fashion', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Outfit thay doi lan 2, celeb drama', contentAngle: 'Met Gala After-Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-miss-usa-miss-universe-style', name: 'Miss USA / Miss Universe-style', category: 'fashion', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam khach moi/giam khao, co runway', contentAngle: 'Miss USA / Miss Universe-style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-multi-camera-sitcom', name: 'Multi-camera sitcom', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu cameo, khan gia cuoi live', contentAngle: 'Multi-camera sitcom works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-name-that-tune', name: 'Name That Tune', category: 'music', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hop am nhac nhe', contentAngle: 'Name That Tune works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-nba-all-star-after-party', name: 'NBA All-Star After-Party', category: 'sports', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu, rapper, model, fashion', contentAngle: 'NBA All-Star After-Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-nba-all-star-celebrity-game', name: 'NBA All-Star Celebrity Game', category: 'sports', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Ca si, dien vien, influencer choi bong, rat de viral', contentAngle: 'NBA All-Star Celebrity Game works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-nba-awards', name: 'NBA Awards', category: 'sports', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'San khau trao giai, outfit, celeb crowd', contentAngle: 'NBA Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-nba-foundation-gala-concept', name: 'NBA Foundation Gala Concept', category: 'concept', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tu dung: bong ro + thoi trang + ca nhac', contentAngle: 'NBA Foundation Gala Concept works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-netflix-premiere-event', name: 'Netflix Premiere Event', category: 'other', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Phim tai lieu the thao, celeb, tham do', contentAngle: 'Netflix Premiere Event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-new-years-rockin-eve', name: 'New Year’s Rockin’ Eve', category: 'music', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Ca si bieu dien, celeb countdown', contentAngle: 'New Year’s Rockin’ Eve works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-new-york-fashion-week-nyfw', name: 'New York Fashion Week – NYFW', category: 'fashion', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu NBA/WNBA ngoi hang ghe dau, outfit viral', contentAngle: 'New York Fashion Week – NYFW works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-nickelodeon-kids-choice-awards', name: 'Nickelodeon Kids’ Choice Awards', category: 'other', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hop vui, mau sac, slime, family audience', contentAngle: 'Nickelodeon Kids’ Choice Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-nike-eybl-showcase-event', name: 'Nike EYBL Showcase Event', category: 'sneaker', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tai nang tre, sneaker, streetwear', contentAngle: 'Nike EYBL Showcase Event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-olympics-watch-party', name: 'Olympics Watch Party', category: 'sports', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'The thao, quoc gia, celeb', contentAngle: 'Olympics Watch Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-oscar-after-party', name: 'Oscar After-Party', category: 'other', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hollywood + athlete + luxury', contentAngle: 'Oscar After-Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-password-pyramid', name: 'Password / Pyramid', category: 'tv', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu choi cung celeb', contentAngle: 'Password / Pyramid works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-peoples-choice-awards', name: 'People’s Choice Awards', category: 'other', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hop celebrity, fan voting, outfit', contentAngle: 'People’s Choice Awards works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-performance-runway-special', name: 'Performance runway special', category: 'fashion', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu xuat hien cung dancer/ca si', contentAngle: 'Performance runway special works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-podcast-live-audience', name: 'Podcast live audience', category: 'tv', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu ke chuyen, reveal fashion collab', contentAngle: 'Podcast live audience works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-prada-linea-rossa-sports-event', name: 'Prada Linea Rossa Sports Event', category: 'fashion', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Sport + fashion, kha hop', contentAngle: 'Prada Linea Rossa Sports Event works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-project-runway-style', name: 'Project Runway style', category: 'fashion', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam guest judge/chu de thiet ke jersey', contentAngle: 'Project Runway style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-robin-hood-gala', name: 'Robin Hood Gala', category: 'fashion', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'New York, giau, sang, tu thien', contentAngle: 'Robin Hood Gala works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-rupauls-drag-race-finale-style', name: 'RuPaul’s Drag Race finale style', category: 'fashion', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Outfit, runway, performance, khan gia', contentAngle: 'RuPaul’s Drag Race finale style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-saturday-night-live-snl', name: 'Saturday Night Live – SNL', category: 'tv', fitScore: 10, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam host, dien hai, ca si khach moi', contentAngle: 'Saturday Night Live – SNL works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-sneaker-expo', name: 'Sneaker Expo', category: 'sneaker', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Giay, streetwear, autograph', contentAngle: 'Sneaker Expo works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-so-you-think-you-can-dance', name: 'So You Think You Can Dance', category: 'tv', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'It hop hon nhung van dung duoc', contentAngle: 'So You Think You Can Dance works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-sports-fashion-sitcom-episode', name: 'Sports fashion sitcom episode', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Dung vui, parody', contentAngle: 'Sports fashion sitcom episode works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-sports-illustrated-gala', name: 'Sports Illustrated Gala', category: 'sports', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'The thao + celeb + style', contentAngle: 'Sports Illustrated Gala works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-sports-memorabilia-expo', name: 'Sports Memorabilia Expo', category: 'sports', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'It fashion hon, hop fan', contentAngle: 'Sports Memorabilia Expo works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-sundance-film-festival', name: 'Sundance Film Festival', category: 'other', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'It flashy hon, hop documentary', contentAngle: 'Sundance Film Festival works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-super-bowl-watch-party', name: 'Super Bowl Watch Party', category: 'sports', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Ca si, rapper, athlete, party', contentAngle: 'Super Bowl Watch Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-the-daily-show', name: 'The Daily Show', category: 'tv', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hop neu cau thu ban chuyen xa hoi/the thao', contentAngle: 'The Daily Show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-the-old-man-and-the-three-draymond-style-show', name: 'The Old Man and the Three / Draymond-style show', category: 'tv', fitScore: 7, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu noi ve lifestyle/fashion/music', contentAngle: 'The Old Man and the Three / Draymond-style show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-the-price-is-right', name: 'The Price Is Right', category: 'tv', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu gay bat ngo cho khan gia', contentAngle: 'The Price Is Right works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-real-housewives-reunion-style', name: 'The Real Housewives Reunion style', category: 'tv', fitScore: 6, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Drama ban gai, celeb, lifestyle', contentAngle: 'The Real Housewives Reunion style works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-vanity-fair-oscar-party', name: 'Vanity Fair Oscar Party', category: 'fashion', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Hollywood sang, celeb lon', contentAngle: 'Vanity Fair Oscar Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-victorias-secret-fashion-show', name: 'Victoria’s Secret Fashion Show', category: 'fashion', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu ngoi front row, ca si hat live, nguoi mau catwalk', contentAngle: 'Victoria’s Secret Fashion Show works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-wheel-of-fortune', name: 'Wheel of Fortune', category: 'tv', fitScore: 5, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu lam celebrity guest', contentAngle: 'Wheel of Fortune works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-wild-n-out', name: 'Wild ’N Out', category: 'tv', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu rap battle, joke, hip-hop vibe', contentAngle: 'Wild ’N Out works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-wireless-style-us-concept', name: 'Wireless-style US concept', category: 'music', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Rap festival, NBA celeb cameo', contentAngle: 'Wireless-style US concept works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-wnba-empowerment-gala', name: 'WNBA Empowerment Gala', category: 'sports', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tu dung: WNBA + thoi trang + ca nhac', contentAngle: 'WNBA Empowerment Gala works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-wnba-finals-watch-party', name: 'WNBA Finals Watch Party', category: 'sports', fitScore: 8, usualWindow: 'Flexible / verify exact schedule', bestUse: 'WNBA, fan, celeb nu, fashion', contentAngle: 'WNBA Finals Watch Party works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-wnba-rising-stars-fashion-night', name: 'WNBA Rising Stars Fashion Night', category: 'sports', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Tu dung, cuc hop cho nu cau thu tre', contentAngle: 'WNBA Rising Stars Fashion Night works as a basketball, fashion, music, or celebrity concept angle.' }),
  createFlexibleEvent({ id: 'txt-youth-basketball-charity-concert', name: 'Youth Basketball Charity Concert', category: 'sports', fitScore: 9, usualWindow: 'Flexible / verify exact schedule', bestUse: 'Cau thu gay quy, rapper bieu dien', contentAngle: 'Youth Basketball Charity Concert works as a basketball, fashion, music, or celebrity concept angle.' }),
]

export const eventTimingRecords: EventTimingRecord[] = [
  {
    id: 'nba-all-star-weekend-2026',
    name: 'NBA All-Star Weekend',
    category: 'sports',
    fitScore: 10,
    startDate: '2026-02-13',
    endDate: '2026-02-15',
    usualWindow: 'Mid February',
    statusNote: '2026 edition ran in Los Angeles / Inglewood.',
    bestUse: 'Basketball, celebrities, live music, tunnel fits, fan events.',
    contentAngle: 'All-Star Weekend turns into a fashion-music takeover.',
    sourceName: 'NBA All-Star 2026 schedule coverage',
    sourceUrl: 'https://www.nba.com/allstar',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'nba-fashion-music-night',
    name: 'NBA All-Star Fashion Music Night',
    category: 'concept',
    fitScore: 10,
    usualWindow: 'Use during NBA All-Star week',
    statusNote: 'Fictional / fan-made format. Do not present as real news.',
    bestUse: 'Safest all-in-one concept for basketball, runway, singers, and audience.',
    contentAngle: 'NBA stars walk the runway as hip-hop legends perform live.',
    sourceName: 'Internal concept format',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'nba-draft-2026',
    name: 'NBA Draft Night',
    category: 'sports',
    fitScore: 9,
    startDate: '2026-06-23',
    endDate: '2026-06-24',
    usualWindow: 'Late June',
    statusNote: '2026 draft is scheduled for two nights at Barclays Center.',
    bestUse: 'Rookies in suits, families, red carpet, interviews, emotional reactions.',
    contentAngle: 'Top prospects arrive in runway-level draft-night suits.',
    sourceName: 'NBA Draft 2026 announcement',
    sourceUrl: 'https://www.nba.com/draft',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'wnba-draft-2026',
    name: 'WNBA Draft',
    category: 'sports',
    fitScore: 9,
    startDate: '2026-04-13',
    endDate: '2026-04-13',
    usualWindow: 'April',
    statusNote: '2026 draft was held after the NCAA women basketball season.',
    bestUse: 'WNBA fashion, rising stars, gowns, suits, empowerment framing.',
    contentAngle: 'WNBA rookies turn draft night into a fashion statement.',
    sourceName: 'WNBA Draft 2026 coverage',
    sourceUrl: 'https://www.wnba.com/draft',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'wnba-all-star-2026',
    name: 'WNBA All-Star Weekend',
    category: 'sports',
    fitScore: 9,
    startDate: '2026-07-24',
    endDate: '2026-07-25',
    usualWindow: 'Mid to late July',
    statusNote: 'Chicago hosts; skills and 3PT on July 24, All-Star Game on July 25.',
    bestUse: 'WNBA stars, fashion, music, activism, fan moments.',
    contentAngle: 'WNBA All-Star Weekend becomes a glam music-night spectacle.',
    sourceName: 'WNBA All-Star 2026 announcement',
    sourceUrl: 'https://www.wnba.com/allstar',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'bet-awards-2026',
    name: 'BET Awards',
    category: 'music',
    fitScore: 10,
    startDate: '2026-06-28',
    endDate: '2026-06-28',
    usualWindow: 'June',
    statusNote: '2026 show is scheduled live from Los Angeles.',
    bestUse: 'NBA, WNBA, hip-hop, R&B, Black culture, red carpet outfits.',
    contentAngle: 'An NBA style icon steals the BET Awards spotlight.',
    sourceName: 'BET / AP 2026 coverage',
    sourceUrl: 'https://www.bet.com/bet-awards',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'mtv-vmas-2026',
    name: 'MTV VMAs',
    category: 'music',
    fitScore: 10,
    startDate: '2026-09-27',
    endDate: '2026-09-27',
    usualWindow: 'Late August to September',
    statusNote: '2026 VMAs are set for the Los Angeles area.',
    bestUse: 'Shock outfits, pop stage, live performance, celebrity reaction shots.',
    contentAngle: 'A basketball star turns the VMAs into a courtside couture moment.',
    sourceName: 'MTV VMAs 2026 date coverage',
    sourceUrl: 'https://www.mtv.com/vma',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'grammys-2026',
    name: 'Grammy Awards',
    category: 'music',
    fitScore: 8,
    startDate: '2026-02-01',
    endDate: '2026-02-01',
    usualWindow: 'January to February',
    statusNote: '2026 ceremony was held at Crypto.com Arena in Los Angeles.',
    bestUse: 'Prestige red carpet, major singers, athlete presenters or VIP guests.',
    contentAngle: 'An NBA guest brings tunnel-fit energy to Grammy night.',
    sourceName: 'Recording Academy / Grammy 2026 coverage',
    sourceUrl: 'https://www.grammy.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'iheartradio-2026',
    name: 'iHeartRadio Music Awards',
    category: 'music',
    fitScore: 8,
    startDate: '2026-03-26',
    endDate: '2026-03-26',
    usualWindow: 'March',
    statusNote: '2026 show was held at Dolby Theatre in Los Angeles.',
    bestUse: 'Pop stage, younger celebrity crowd, broadcast-friendly viral clips.',
    contentAngle: 'A basketball guest joins a surprise live pop performance.',
    sourceName: 'iHeartRadio 2026 coverage',
    sourceUrl: 'https://www.iheart.com/music-awards',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'american-music-awards-2026',
    name: 'American Music Awards',
    category: 'music',
    fitScore: 8,
    startDate: '2026-05-25',
    endDate: '2026-05-25',
    usualWindow: 'May or fall, varies by year',
    statusNote: '2026 show was scheduled for Las Vegas.',
    bestUse: 'Pop performers, celebrity guests, red carpet, crowd reaction.',
    contentAngle: 'A courtside-inspired outfit goes viral at the AMAs.',
    sourceName: 'AMAs 2026 coverage',
    sourceUrl: 'https://www.theamas.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'met-gala-2026',
    name: 'Met Gala',
    category: 'fashion',
    fitScore: 10,
    startDate: '2026-05-04',
    endDate: '2026-05-04',
    usualWindow: 'First Monday in May',
    statusNote: '2026 gala was held on May 4.',
    bestUse: 'Luxury outfits, red carpet, flash photography, global viral fashion.',
    contentAngle: 'A basketball superstar shuts down the Met Gala carpet.',
    sourceName: 'The Met / Vogue calendar',
    sourceUrl: 'https://www.metmuseum.org',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'nyfw-september-2026',
    name: 'New York Fashion Week',
    category: 'fashion',
    fitScore: 10,
    usualWindow: 'February and September',
    statusNote: 'Semiannual; use September 2026 for the next fresh fashion window.',
    bestUse: 'Front row athletes, runway, designer collabs, street style.',
    contentAngle: 'WNBA and NBA stars take over the NYFW front row.',
    sourceName: 'CFDA fashion calendar',
    sourceUrl: 'https://cfda.com/fashion-calendar',
    sourcePublishedAt: '2026-04-17',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'cfda-awards-2026',
    name: 'CFDA Fashion Awards',
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Usually November',
    statusNote: '2026 date was not locked in during this verification pass.',
    bestUse: 'Style icon awards, designer collaborations, fashion-industry legitimacy.',
    contentAngle: 'A basketball style icon is honored by the fashion industry.',
    sourceName: 'CFDA',
    sourceUrl: 'https://cfda.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'victorias-secret-style',
    name: "Victoria's Secret Fashion Show style",
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Typically fall or custom concept',
    statusNote: 'Use as style reference unless a current official date is confirmed.',
    bestUse: 'Runway, singer performance, models, front-row athlete reactions.',
    contentAngle: 'Basketball celebrities stun front row during a live runway performance.',
    sourceName: 'Style-reference concept',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'coachella-2026',
    name: 'Coachella',
    category: 'festival',
    fitScore: 9,
    startDate: '2026-04-10',
    endDate: '2026-04-19',
    usualWindow: 'Two weekends in April',
    statusNote: '2026 festival ran April 10-12 and April 17-19.',
    bestUse: 'Festival outfits, VIP crowd, celebrity sightings, huge stages.',
    contentAngle: 'NBA stars bring courtside streetwear to the Coachella VIP crowd.',
    sourceName: 'Coachella 2026 lineup coverage',
    sourceUrl: 'https://www.coachella.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'rolling-loud-2026',
    name: 'Rolling Loud Orlando',
    category: 'festival',
    fitScore: 10,
    startDate: '2026-05-08',
    endDate: '2026-05-10',
    usualWindow: 'Varies by city',
    statusNote: '2026 U.S. edition ran May 8-10 at Camping World Stadium.',
    bestUse: 'Rap, NBA culture, streetwear, sneaker fits, loud crowd energy.',
    contentAngle: 'NBA stars take over Rolling Loud with courtside-inspired streetwear.',
    sourceName: 'Rolling Loud 2026 coverage',
    sourceUrl: 'https://www.rollingloud.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'complexcon',
    name: 'ComplexCon',
    category: 'sneaker',
    fitScore: 10,
    usualWindow: 'Usually announced by city/year',
    statusNote: 'Check current city schedule before posting as a real event.',
    bestUse: 'Sneaker, streetwear, rap, athlete cameo, booth launches.',
    contentAngle: 'NBA stars surprise fans with a streetwear runway at ComplexCon.',
    sourceName: 'ComplexCon',
    sourceUrl: 'https://www.complexcon.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'sneaker-con',
    name: 'Sneaker Con',
    category: 'sneaker',
    fitScore: 9,
    usualWindow: 'Multiple cities year-round',
    statusNote: 'Pick the exact city/date from the official schedule for real posts.',
    bestUse: 'Sneaker collectors, athlete signings, fan meetups, resale culture.',
    contentAngle: 'A signature sneaker reveal shocks collectors at Sneaker Con.',
    sourceName: 'Sneaker Con schedule',
    sourceUrl: 'https://sneakercon.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'jordan-brand-fashion-show',
    name: 'Jordan Brand Fashion Show',
    category: 'sneaker',
    fitScore: 10,
    usualWindow: 'No fixed public calendar',
    statusNote: 'Best used as a fictional brand concept unless officially announced.',
    bestUse: 'Signature shoes, runway, NBA stars, live hip-hop performance.',
    contentAngle: 'Jordan Brand stages a runway show with NBA stars and live rap.',
    sourceName: 'Brand-concept format',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'gq-men-of-the-year',
    name: 'GQ Men of the Year Party',
    category: 'fashion',
    fitScore: 9,
    usualWindow: 'Usually November',
    statusNote: 'Use the current year announcement when making a real-date post.',
    bestUse: 'Luxury menswear, style icons, NBA fashion personalities.',
    contentAngle: 'NBA style icons take over a GQ party with luxury tunnel fits.',
    sourceName: 'GQ event coverage',
    sourceUrl: 'https://www.gq.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'the-masked-singer',
    name: 'The Masked Singer',
    category: 'tv',
    fitScore: 10,
    usualWindow: 'TV season varies',
    statusNote: 'Use as a What If concept for athlete singing surprises.',
    bestUse: 'A basketball superstar secretly performs and shocks the judges.',
    contentAngle: 'A masked basketball legend leaves the crowd speechless.',
    sourceName: 'TV-format concept',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'snl',
    name: 'Saturday Night Live',
    category: 'tv',
    fitScore: 10,
    usualWindow: 'Usually fall through spring',
    statusNote: 'Real episodes need host/date verification; concept use is flexible.',
    bestUse: 'Athlete host, comedy sketch, musical guest, live audience.',
    contentAngle: 'An NBA star hosts SNL and joins the musical guest on stage.',
    sourceName: 'NBC / SNL schedule',
    sourceUrl: 'https://www.nbc.com/saturday-night-live',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'dancing-with-the-stars',
    name: 'Dancing with the Stars',
    category: 'tv',
    fitScore: 9,
    usualWindow: 'Usually fall season',
    statusNote: 'Use current season cast/date if posting as real entertainment news.',
    bestUse: 'Athlete dancing, stage outfits, audience votes, viral performance.',
    contentAngle: 'A basketball star trades sneakers for a ballroom-stage look.',
    sourceName: 'TV-format concept',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'nba-finals-watch-party',
    name: 'NBA Finals Watch Party',
    category: 'other',
    fitScore: 8,
    usualWindow: 'During NBA Finals',
    statusNote: 'Use the live game schedule if posting against a real matchup.',
    bestUse: 'Large screens, celebrity audience, singer before or after the game.',
    contentAngle: 'A Finals watch party turns into a surprise fashion-music night.',
    sourceName: 'Flexible event format',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'fanatics-fest',
    name: 'Fanatics Fest',
    category: 'other',
    fitScore: 10,
    usualWindow: 'Varies by annual announcement',
    statusNote: 'Verify the active city and dates before using as real news.',
    bestUse: 'Athletes, fans, autographs, sports panels, merch and media moments.',
    contentAngle: 'NBA stars surprise fans with a stage reveal at Fanatics Fest.',
    sourceName: 'Fanatics Fest',
    sourceUrl: 'https://www.fanaticsfest.com',
    verifiedAt: '2026-06-17',
  },
  {
    id: 'charity-fashion-gala',
    name: 'Celebrity Charity Fashion Gala',
    category: 'other',
    fitScore: 8,
    usualWindow: 'Flexible / seasonal',
    statusNote: 'Best as a fictional or charity concept unless tied to a named gala.',
    bestUse: 'Red carpet, VIP audience, singers, auction, athlete philanthropy.',
    contentAngle: 'Basketball stars walk a charity runway while R&B artists perform.',
    sourceName: 'Flexible event format',
    verifiedAt: '2026-06-17',
  },
  ...flexibleShowRecords,
]

export function parseEventDate(value?: string) {
  if (!value) {
    return null
  }

  const [year, month, day] = value.split('-').map(Number)
  return new Date(year, month - 1, day)
}

export function getEventPhase(event: EventTimingRecord, today = new Date()): EventPhase {
  const start = parseEventDate(event.startDate)
  const end = parseEventDate(event.endDate ?? event.startDate)

  if (!start || !end) {
    return event.category === 'concept' ? 'concept' : 'tba'
  }

  const normalizedToday = new Date(today.getFullYear(), today.getMonth(), today.getDate())

  if (normalizedToday < start) {
    return 'upcoming'
  }

  if (normalizedToday > end) {
    return 'past'
  }

  return 'today'
}

export function formatEventDateRange(event: EventTimingRecord) {
  if (!event.startDate) {
    return event.usualWindow
  }

  const start = parseEventDate(event.startDate)
  const end = parseEventDate(event.endDate ?? event.startDate)

  if (!start || !end) {
    return event.usualWindow
  }

  const formatter = new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })

  if (event.startDate === event.endDate || !event.endDate) {
    return formatter.format(start)
  }

  return `${formatter.format(start)} - ${formatter.format(end)}`
}

export function getDaysUntil(event: EventTimingRecord, today = new Date()) {
  const start = parseEventDate(event.startDate)
  if (!start) {
    return null
  }

  const normalizedToday = new Date(today.getFullYear(), today.getMonth(), today.getDate()).getTime()
  return Math.ceil((start.getTime() - normalizedToday) / 86400000)
}

export function buildEventTimingCopy(events: EventTimingRecord[], today = new Date()) {
  const date = today.toISOString().slice(0, 10)
  const lines = [
    `Event timing board - updated ${date}`,
    '',
    'Event | Time | Status | Best use',
    '--- | --- | --- | ---',
  ]

  events.forEach((event) => {
    const phase = getEventPhase(event, today)
    lines.push(
      `${event.name} | ${formatEventDateRange(event)} | ${phase.toUpperCase()} | ${event.bestUse}`
    )
  })

  return lines.join('\n')
}
