import type { FacebookPage, Post, Notification } from './types'

export const mockPages: FacebookPage[] = [
  {
    id: 'page-1',
    name: 'Tech News Daily',
    pageUrl: 'https://facebook.com/technewsdaily',
    logoUrl: 'https://picsum.photos/seed/page-logo-tech/80/80',
    brandColor: '#14b8a6',
    isActive: true,
    postsPerDay: 5,
    timeSlots: ['08:00', '10:30', '13:00', '16:00', '20:00'],
    notes: 'Focus on AI and startup news',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'page-2',
    name: 'Food & Recipes VN',
    pageUrl: 'https://facebook.com/foodrecipesvn',
    logoUrl: 'https://picsum.photos/seed/page-logo-food/80/80',
    brandColor: '#f97316',
    isActive: true,
    postsPerDay: 5,
    timeSlots: ['07:30', '09:30', '11:30', '15:30', '19:30'],
    notes: 'Vietnamese cuisine content',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'page-3',
    name: 'Travel Vietnam',
    pageUrl: 'https://facebook.com/travelvietnam',
    logoUrl: 'https://picsum.photos/seed/page-logo-travel/80/80',
    brandColor: '#0ea5e9',
    isActive: true,
    postsPerDay: 4,
    timeSlots: ['08:00', '12:00', '17:00', '21:00'],
    notes: 'Tourism and travel tips',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'page-4',
    name: 'Fitness Tips',
    pageUrl: 'https://facebook.com/fitnesstips',
    logoUrl: 'https://picsum.photos/seed/page-logo-fitness/80/80',
    brandColor: '#22c55e',
    isActive: true,
    postsPerDay: 3,
    timeSlots: ['06:00', '12:00', '18:00'],
    notes: 'Health and workout content',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-19'),
  },
  {
    id: 'page-5',
    name: 'Pet Lovers Community',
    pageUrl: 'https://facebook.com/petlovers',
    logoUrl: 'https://picsum.photos/seed/page-logo-pet/80/80',
    brandColor: '#a855f7',
    isActive: false,
    postsPerDay: 4,
    timeSlots: ['09:00', '13:00', '17:00', '20:00'],
    notes: 'Currently paused - reviewing content strategy',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-03-01'),
  },
]

const today = new Date().toISOString().split('T')[0]

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    pageId: 'page-1',
    postDate: today,
    timeSlot: '08:00',
    imageUrl: 'https://picsum.photos/seed/tech1/400/300',
    caption: 'Breaking: New AI model released by OpenAI shows remarkable improvements in reasoning capabilities. Read more about GPT-5 features.',
    adsLink: 'https://example.com/ai-news',
    status: 'posted',
    notes: 'High engagement expected',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-2',
    pageId: 'page-1',
    postDate: today,
    timeSlot: '10:30',
    imageUrl: 'https://picsum.photos/seed/tech2/400/300',
    caption: 'Top 10 startups to watch in 2024. These companies are revolutionizing their industries.',
    status: 'posted',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-3',
    pageId: 'page-1',
    postDate: today,
    timeSlot: '13:00',
    imageUrl: 'https://picsum.photos/seed/tech3/400/300',
    caption: 'Tech giants announce new partnership for sustainable computing initiatives.',
    adsLink: 'https://example.com/green-tech',
    status: 'late',
    notes: 'Forgot to post on time',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-4',
    pageId: 'page-1',
    postDate: today,
    timeSlot: '16:00',
    imageUrl: 'https://picsum.photos/seed/tech4/400/300',
    caption: 'Cybersecurity tips for remote workers. Protect your data while working from home.',
    status: 'scheduled',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-6',
    pageId: 'page-2',
    postDate: today,
    timeSlot: '07:30',
    imageUrl: 'https://picsum.photos/seed/food1/400/300',
    caption: 'Recipe: Perfect Pho Bo - Traditional Vietnamese beef noodle soup with all the authentic flavors.',
    status: 'posted',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-7',
    pageId: 'page-2',
    postDate: today,
    timeSlot: '09:30',
    imageUrl: 'https://picsum.photos/seed/food2/400/300',
    caption: 'Banh Mi secrets: How to make the crispiest Vietnamese baguette at home.',
    status: 'posted',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-8',
    pageId: 'page-2',
    postDate: today,
    timeSlot: '11:30',
    imageUrl: 'https://picsum.photos/seed/food3/400/300',
    caption: 'Summer rolls with peanut sauce - Fresh and healthy Vietnamese appetizer.',
    status: 'due_now',
    notes: 'Ready to post',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-9',
    pageId: 'page-2',
    postDate: today,
    timeSlot: '15:30',
    imageUrl: 'https://picsum.photos/seed/food4/400/300',
    caption: 'Vietnamese iced coffee - The ultimate guide to making Ca Phe Sua Da.',
    status: 'ready',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-10',
    pageId: 'page-2',
    postDate: today,
    timeSlot: '19:30',
    caption: 'Evening dessert: Che Ba Mau recipe coming soon!',
    status: 'draft',
    notes: 'Need to take photos',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-11',
    pageId: 'page-3',
    postDate: today,
    timeSlot: '08:00',
    imageUrl: 'https://picsum.photos/seed/travel1/400/300',
    caption: 'Ha Long Bay at sunrise - A magical experience you cannot miss when visiting Vietnam.',
    status: 'posted',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-12',
    pageId: 'page-3',
    postDate: today,
    timeSlot: '12:00',
    imageUrl: 'https://picsum.photos/seed/travel2/400/300',
    caption: 'Hidden gems of Hoi An: Local spots tourists rarely discover.',
    status: 'late',
    notes: 'Delayed due to content review',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-13',
    pageId: 'page-4',
    postDate: today,
    timeSlot: '06:00',
    imageUrl: 'https://picsum.photos/seed/fitness1/400/300',
    caption: 'Morning workout routine: 15 minutes to energize your entire day.',
    status: 'posted',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-14',
    pageId: 'page-4',
    postDate: today,
    timeSlot: '12:00',
    imageUrl: 'https://picsum.photos/seed/fitness2/400/300',
    caption: 'Healthy lunch ideas for busy professionals. Quick, nutritious, and delicious!',
    status: 'scheduled',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'post-15',
    pageId: 'page-4',
    postDate: today,
    timeSlot: '18:00',
    imageUrl: 'https://picsum.photos/seed/fitness3/400/300',
    caption: 'Post-work stretching exercises to relieve stress and tension.',
    status: 'ready',
    notes: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'error',
    title: 'Late Post',
    message: 'Tech News Daily 13:00 post is overdue',
    postId: 'post-3',
    pageId: 'page-1',
    timeSlot: '13:00',
    timestamp: new Date(),
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'error',
    title: 'Late Post',
    message: 'Travel Vietnam 12:00 post is overdue',
    postId: 'post-12',
    pageId: 'page-3',
    timeSlot: '12:00',
    timestamp: new Date(),
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'warning',
    title: 'Missing Slot',
    message: 'Tech News Daily has no post for 20:00',
    pageId: 'page-1',
    timeSlot: '20:00',
    timestamp: new Date(),
    isRead: false,
  },
  {
    id: 'notif-4',
    type: 'warning',
    title: 'Missing Slots',
    message: 'Travel Vietnam missing 2 slots today (17:00, 21:00)',
    pageId: 'page-3',
    timestamp: new Date(),
    isRead: false,
  },
  {
    id: 'notif-5',
    type: 'info',
    title: 'Due Soon',
    message: 'Food & Recipes VN 11:30 post due in 15 minutes',
    postId: 'post-8',
    pageId: 'page-2',
    timeSlot: '11:30',
    timestamp: new Date(),
    isRead: true,
  },
  {
    id: 'notif-6',
    type: 'success',
    title: 'Post Published',
    message: 'Tech News Daily 10:30 post marked as posted',
    postId: 'post-2',
    pageId: 'page-1',
    timeSlot: '10:30',
    timestamp: new Date(Date.now() - 3600000),
    isRead: true,
  },
]
